'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InwardEntry

    '''<summary>
    '''codeBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents codeBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TitleBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''periodicity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents periodicity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''VolNoBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VolNoBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''IssueNoBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IssueNoBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FromDateBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDateBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ToDateBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDateBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MergeRemarkBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MergeRemarkBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''issueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents issueDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''saveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents saveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''clear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updateSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete As Global.System.Web.UI.WebControls.Button
End Class
