'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report1

    '''<summary>
    '''List1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents List1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''List2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents List2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Groupby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Groupby As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''List3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents List3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Journals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Journals As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Publishers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Publishers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''jpubl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpubl As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''periodicityl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents periodicityl As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''jdeptl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jdeptl As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''jprogl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jprogl As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''issuesl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents issuesl As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''subdis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subdis As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''subapp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subapp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''subavl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subavl As Global.System.Web.UI.WebControls.GridView
End Class
